name: bus_pass_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  intl: ^0.19.0
  qr_flutter: ^4.0.0
  mobile_scanner: 3.2.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.9
  razorpay_flutter: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/st_logo.jpeg
